project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  preview:
    port: 3333

execute:
  freeze: auto # re-render only when source changes

website:
  title: "Data Analytics for Sciences"
  description: "An Introduction to Data Science in Excel and R"
  site-url: "https://ckaoxvii.github.io/CIS-351-Data-Analytics-for-Sciences/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  
  # announcement:
  #   icon: calendar-check
  #   content: "*Test!*"
  #   type: danger
  #   position: below-navbar


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



